version: "3.2"
services:
  server:
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.5"
    build: /home/vagrant/server
    command: python /home/otus/server/signal_server.py
    #pids_limit: "10"
    ports:
      - 127.0.0.1:8088:8088
      - 10.0.2.15:8088:8088
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure:5
    security_opt:
      - no-new-privileges
#    read_only: true
#  client:
#    build: /home/vagrant/client
#    command: python ./signal_client.py
#    network_mode: host
#    depends_on:
#      - server
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8088 || exit 1"]
#      interval: 5s
#      timeout: 10s
#      retries: 3
