---
- hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
  - name: install requirements
    apt:
      pkg:
        - curl
        - apt-transport-https
        - lsb-release
      state: latest
  - name: Insall the GPG key
    apt_key:
      url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
      state: present
  - apt_repository:
      repo: deb https://packages.wazuh.com/3.x/apt/ stable main
      state: present
  - name: install wazuh
    apt:
      pkg:
        - wazuh-manager
      state: latest
      update_cache: yes
  - name: filebeat config
    command: "{{ item }}"
    with_items:
      - curl -so /usr/src/nodejs_setup_10.x https://deb.nodesource.com/setup_10.x
      - bash /usr/src/nodejs_setup_10.x
  - name: install wazuh
    apt:
      pkg:
        - nodejs
        - wazuh-api
      state: latest
      update_cache: yes
  - name: Insall the GPG key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present
  - name: install filebeat
    apt:
      pkg:
        - filebeat=7.6.2
      update_cache: yes
  - name: filebeat config
    command: "{{ item }}"
    with_items:
      - curl -so /etc/filebeat/filebeat.yml https://raw.githubusercontent.com/wazuh/wazuh/v3.12.2/extensions/filebeat/7.x/filebeat.yml
      - curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.12.2/extensions/elasticsearch/7.x/wazuh-template.json
      - curl -so /usr/src/wazuh-filebeat-0.1.tar.gz https://packages.wazuh.com/3.x/filebeat/wazuh-filebeat-0.1.tar.gz 
      - tar -xvf /usr/src/wazuh-filebeat-0.1.tar.gz -C /usr/share/filebeat/module/ 
  - name: Config ELT ip
    replace:
      path: /etc/filebeat/filebeat.yml
      regexp: 'YOUR_ELASTIC_SERVER_IP'
      replace: '127.0.0.1'
  - name: Insall the GPG key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present
  - name: install ELT
    apt:
      pkg:
        - elasticsearch=7.6.2
        - kibana=7.6.2
      update_cache: yes
  - name: ELT config
    blockinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      block: |
        network.host: 127.0.0.1
        node.name: node-1
        cluster.initial_master_nodes: ["node-1"]
  - name: filebeat config
    command: "{{ item }}"
    args:
      chdir: /usr/share/kibana/
    with_items:
      - sudo -u kibana bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.12.2_7.6.2.zip
  - name: kibana config
    blockinfile:
      path: /etc/kibana/kibana.yml
      block: |
        server.host: "0.0.0.0"
        elasticsearch.hosts: ["http://127.0.0.1:9200"]
  - name: enable ELT services
    systemd:
      state: restarted
      enabled: yes
      name: elasticsearch.service
  - name: enable filebeat services
    systemd:
      state: restarted
      enabled: yes
      name: filebeat.service
  - name: enable kibana services
    systemd:
      state: restarted
      enabled: yes
      name: kibana.service
